In [1]:
import pandas as pd
df=pd.read_csv(r"Results_MADE.csv")
df

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0            7.5              9.95  7.85                               0.15   
1           11.0              9.65  7.70                               0.45   
2            7.5              9.90  7.65                               0.55   
3            8.5              9.65  7.55                               0.35   
4           10.0              9.55  7.80                               0.25   
..           ...               ...   ...                                ...   
290         28.0              6.95  7.85                               0.37   
291         28.0              6.90  7.95                               0.60   
292         25.0              7.40  7.70                               0.55   
293         28.0              6.75  7.90                               0.70   
294         28.5              6.50  7.95                               0.90   

     Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                                90.00            0.255   
1                               205.00            0.200   
2                               100.00            0.100   
3                               300.00            0.250   
4                               190.00            0.150   
..                                 ...              ...   
290                              28.00            0.115   
291                              27.75            0.150   
292                              60.75            0.500   
293                              35.00            0.000   
294                             140.00            0.000   

     Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                             22.5                         180.0   
1                             62.5                         410.0   
2                             26.0                         200.0   
3                             97.5                         600.0   
4                             47.5                         380.0   
..                             ...                           ...   
290                           25.0                          56.0   
291                           23.0                          55.5   
292                           15.0                         121.5   
293                           27.0                          70.0   
294                           79.5                         280.0   

     Conductivity (mho/ Cm)          WQI  
0                     134.5    27.143963  
1                      77.0    15.780001  
2                     101.5    20.612438  
3                     148.0    29.820475  
4                     106.0    21.498569  
..                      ...          ...  
290                   281.5    56.181191  
291                   274.0    54.711315  
292                   286.0    57.114775  
293                  1572.5   311.545107  
294                  9272.0  1834.549110  

[295 rows x 10 columns]

In [2]:
df["Temperature"]=df["Temperature"].apply(lambda x:int(x))

In [3]:
df["Dissolved Oxygen"]=df["Dissolved Oxygen"].apply(lambda x:int(x))

In [4]:
df["Temperature"]=df["Temperature"].replace(0,df["Temperature"].mean())

In [5]:
df["Dissolved Oxygen"]=df["Dissolved Oxygen"].replace(0,df["Dissolved Oxygen"].mean())

In [6]:
df["Bio-Chemical Oxygen Demand (mg/L)"]=df["Bio-Chemical Oxygen Demand (mg/L)"].replace(0,df["Bio-Chemical Oxygen Demand (mg/L)"].mean())

In [7]:
df["Faecal Streptococci (MPN/ 100 mL)"]=df["Faecal Streptococci (MPN/ 100 mL)"].replace(0,df["Faecal Streptococci (MPN/ 100 mL)"].mean())

In [8]:
df["Nitrate (mg/ L)"]=df["Nitrate (mg/ L)"].replace(0,df["Nitrate (mg/ L)"].mean())

In [9]:
df["Faecal Coliform (MPN/ 100 mL)"]=df["Faecal Coliform (MPN/ 100 mL)"].replace(0,df["Faecal Coliform (MPN/ 100 mL)"].mean())

In [10]:
df["Total Coliform (MPN/ 100 mL)"]=df["Total Coliform (MPN/ 100 mL)"].replace(0,df["Total Coliform (MPN/ 100 mL)"].mean())

In [11]:
df["Conductivity (mho/ Cm)"]=df["Conductivity (mho/ Cm)"].replace(0,df["Conductivity (mho/ Cm)"].mean())

In [12]:
df.describe()

Temperature  Dissolved Oxygen          pH  \
count   295.000000        295.000000  295.000000   
mean     20.843735          6.917771    7.754627   
std       5.685104          1.823914    0.378879   
min       6.000000          1.000000    5.350000   
25%      18.000000          6.000000    7.550000   
50%      22.000000          7.000000    7.750000   
75%      25.000000          8.000000    8.000000   
max      30.000000         10.000000    8.600000   

       Bio-Chemical Oxygen Demand (mg/L)  Faecal Streptococci (MPN/ 100 mL)  \
count                         295.000000                         295.000000   
mean                            3.664276                        8652.407238   
std                             9.018843                       26074.925591   
min                             0.100000                           1.000000   
25%                             0.925000                         109.750000   
50%                             1.700000                        1000.000000   
75%                             3.500000                        7463.333729   
max                           123.500000                      229000.000000   

       Nitrate (mg/ L)  Faecal Coliform (MPN/ 100 mL)  \
count       295.000000                     295.000000   
mean          1.048051                    6936.990846   
std           1.364621                   22789.863466   
min           0.100000                       1.800000   
25%           0.500000                      30.775000   
50%           0.850000                     605.000000   
75%           0.950000                    5983.661695   
max          14.050000                  251000.000000   

       Total Coliform (MPN/ 100 mL)  Conductivity (mho/ Cm)          WQI  
count                    295.000000              295.000000   295.000000  
mean                   17304.814476              503.561901   100.889437  
std                    52149.851183              797.772721   158.115301  
min                        2.000000               31.500000     0.524595  
25%                      219.500000              209.000000    42.010910  
50%                     2000.000000              300.000000    60.379172  
75%                    14926.667458              441.000000    90.120883  
max                   458000.000000             9272.000000  1834.549110

In [13]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [14]:
X

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0            7.0               9.0  7.85                               0.15   
1           11.0               9.0  7.70                               0.45   
2            7.0               9.0  7.65                               0.55   
3            8.0               9.0  7.55                               0.35   
4           10.0               9.0  7.80                               0.25   
..           ...               ...   ...                                ...   
290         28.0               6.0  7.85                               0.37   
291         28.0               6.0  7.95                               0.60   
292         25.0               7.0  7.70                               0.55   
293         28.0               6.0  7.90                               0.70   
294         28.0               6.0  7.95                               0.90   

     Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                                90.00         0.255000   
1                               205.00         0.200000   
2                               100.00         0.100000   
3                               300.00         0.250000   
4                               190.00         0.150000   
..                                 ...              ...   
290                              28.00         0.115000   
291                              27.75         0.150000   
292                              60.75         0.500000   
293                              35.00         0.870915   
294                             140.00         0.870915   

     Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                             22.5                         180.0   
1                             62.5                         410.0   
2                             26.0                         200.0   
3                             97.5                         600.0   
4                             47.5                         380.0   
..                             ...                           ...   
290                           25.0                          56.0   
291                           23.0                          55.5   
292                           15.0                         121.5   
293                           27.0                          70.0   
294                           79.5                         280.0   

     Conductivity (mho/ Cm)  
0                     134.5  
1                      77.0  
2                     101.5  
3                     148.0  
4                     106.0  
..                      ...  
290                   281.5  
291                   274.0  
292                   286.0  
293                  1572.5  
294                  9272.0  

[295 rows x 9 columns]

In [15]:
Y

0        27.143963
1        15.780001
2        20.612438
3        29.820475
4        21.498569
          ...     
290      56.181191
291      54.711315
292      57.114775
293     311.545107
294    1834.549110
Name: WQI, Length: 295, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=45)

In [17]:
# # from sklearn.ensemble import RandomForestClassifier
# # from sklearn.svm import SVC
# from sklearn.naive_bayes import GaussianNB
from sklearn import linear_model
model = linear_model.LinearRegression()

In [18]:
# model=RandomForestClassifier()
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)

In [19]:
from sklearn.metrics import r2_score
print(r2_score(Y_test,y_pred))

0.9999797819323503


In [20]:
y_pred.round()

array([  50.,   64.,   56.,   21.,   23.,   60.,   92.,   55.,   24.,
         34.,   84.,   27., 1140.,   58.,   55.,   47.,   30.,   94.,
         55.,   22.,  256.,   68.,   88.,   84.,   41.,   62.,   24.,
        480.,   55.,  445.,  100.,   52.,   87.,   87.,  117.,   25.,
         79.,  149.,   16.,   70.,  120.,   57.,  126.,  113.,  182.,
         85.,  242.,   25.,   68.,   43.,   68.,   41.,   20.,   64.,
         29.,  676.,  176.,   43.,   12.])

In [21]:
Y_test.round()

33       51.0
184      65.0
280      56.0
4        21.0
246      24.0
282      60.0
159      91.0
100      55.0
243      25.0
104      34.0
212      85.0
0        27.0
151    1140.0
30       59.0
290      56.0
13       47.0
3        30.0
146      94.0
79       54.0
251      24.0
38      256.0
205      69.0
204      88.0
257      86.0
122      42.0
188      63.0
96       23.0
89      480.0
45       56.0
288     446.0
176     100.0
140      53.0
143      87.0
145      87.0
157     116.0
235      26.0
162      79.0
47      149.0
1        16.0
214      71.0
61      119.0
194      58.0
101     126.0
177     113.0
83      183.0
156      86.0
227     243.0
115      25.0
222      69.0
139      44.0
279      68.0
25       42.0
8        20.0
69       63.0
46       29.0
226     677.0
80      175.0
166      43.0
255      13.0
Name: WQI, dtype: float64

In [28]:
import pickle

In [34]:
with open("nik_model.pkl","wb") as f:
    pickle.dump(model,f)

In [35]:
with open("nik_model.pkl","rb") as f:
    mp=pickle.load(f)

In [69]:
mp.predict(X_test)

array([  49.92569505,   63.56172119,   55.66951868,   21.37916875,
         23.10842065,   59.96064698,   91.54186555,   54.54352923,
         24.3546691 ,   33.75214214,   83.79391092,   27.27951838,
       1139.89853003,   58.17105373,   55.13984879,   46.94030692,
         29.61931161,   93.80619981,   54.88921512,   22.25976799,
        256.17235654,   67.55691805,   87.5991525 ,   84.43869498,
         40.56570149,   62.23509946,   24.1383685 ,  480.31953808,
         55.41130263,  445.35129156,  100.16536517,   52.42740605,
         86.87396394,   86.77816918,  117.12234866,   24.83829106,
         79.07825801,  149.4903339 ,   15.50012261,   70.07056965,
        119.7419818 ,   57.3665432 ,  126.1863524 ,  113.17216374,
        182.38767737,   85.03617503,  241.72875074,   24.59662584,
         68.03372526,   42.66956166,   68.09467079,   41.09761716,
         19.84156085,   64.09042531,   28.55456227,  675.55155769,
        175.65762108,   43.41676781,   11.84117421])

In [70]:
import numpy as np


In [73]:
mp.predict(list(np.array([1,1,1,1,1,1,1,1,1]).reshape(1,-1)))

C:\Users\surya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-4.22680933])